# Dataset

In [2]:
import torch

In [ ]:
# 정의한 영역(Domain)을 촘촘한 점들로 나누어 좌표계 리스트를 만든다.
# 수치해석에서 데이터를 뿌려 학습, 계산
def collocation_points(*args):
    grids = torch.meshgrid(*args, indexing='ij')
    coordinates = torch.stack(grids, dim=len(args)).reshape(-1, len(args))
    return coordinates

In [4]:
nt = 3
nx = 3
t = torch.linspace(0, 1, nt)
x = torch.linspace(-1, 1, nx)
cdata = collocation_points(t, x)
print(cdata.shape, "\n", cdata)

torch.Size([9, 2]) 
 tensor([[ 0.0000, -1.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  1.0000],
        [ 0.5000, -1.0000],
        [ 0.5000,  0.0000],
        [ 0.5000,  1.0000],
        [ 1.0000, -1.0000],
        [ 1.0000,  0.0000],
        [ 1.0000,  1.0000]])


In [ ]:
ny = 3
y = torch.linspace(-1, 1, ny)
cdata = collocation_points(t, x, y)
print(cdata.shape, "\n", cdata) # t =0 일때 x, y 좌표, t = 0.5 일때, ... 해서 3**3개

torch.Size([27, 3]) 
 tensor([[ 0.0000, -1.0000, -1.0000],
        [ 0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000,  1.0000],
        [ 0.0000,  0.0000, -1.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  1.0000],
        [ 0.0000,  1.0000, -1.0000],
        [ 0.0000,  1.0000,  0.0000],
        [ 0.0000,  1.0000,  1.0000],
        [ 0.5000, -1.0000, -1.0000],
        [ 0.5000, -1.0000,  0.0000],
        [ 0.5000, -1.0000,  1.0000],
        [ 0.5000,  0.0000, -1.0000],
        [ 0.5000,  0.0000,  0.0000],
        [ 0.5000,  0.0000,  1.0000],
        [ 0.5000,  1.0000, -1.0000],
        [ 0.5000,  1.0000,  0.0000],
        [ 0.5000,  1.0000,  1.0000],
        [ 1.0000, -1.0000, -1.0000],
        [ 1.0000, -1.0000,  0.0000],
        [ 1.0000, -1.0000,  1.0000],
        [ 1.0000,  0.0000, -1.0000],
        [ 1.0000,  0.0000,  0.0000],
        [ 1.0000,  0.0000,  1.0000],
        [ 1.0000,  1.0000, -1.0000],
        [ 1.0000,  1.0000,  0.0000],
        [ 1.0000

In [ ]:
u0 = torch.sin(x) # 여기서 x는 위에서 정의한 [-1 0 1]이다

# 초기 조건 설정
initdata = collocation_points(t[0], x)
print(initdata.shape, "\n", initdata)

torch.Size([3, 2]) 
 tensor([[ 0., -1.],
        [ 0.,  0.],
        [ 0.,  1.]])


In [7]:
u0

tensor([-0.8415,  0.0000,  0.8415])

In [9]:
# 경계 조건 설정
xbg = torch.FloatTensor([x[0], x[-1]])
bgdata = collocation_points(t, xbg)
print(bgdata.shape, "\n", bgdata)

torch.Size([6, 2]) 
 tensor([[ 0.0000, -1.0000],
        [ 0.0000,  1.0000],
        [ 0.5000, -1.0000],
        [ 0.5000,  1.0000],
        [ 1.0000, -1.0000],
        [ 1.0000,  1.0000]])


In [21]:
class MyData(torch.utils.data.Dataset):
    def __init__(self, cdata):
        self.cdata = cdata
        self.len  = len(cdata)

    def __len__(self):
        return self.len
    
    def __getitem__(self, index):
        return self.cdata[index]
    
batch = 8
train_loader = torch.utils.data.DataLoader(MyData(cdata), batch_size=batch, shuffle=True)

In [19]:
data_iter = iter(train_loader)
batch_data = next(data_iter)

In [20]:
batch_data

tensor([[ 0.5000, -1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000],
        [ 0.5000,  0.0000,  1.0000],
        [ 0.5000,  0.0000,  0.0000],
        [ 0.5000,  1.0000, -1.0000],
        [ 0.0000,  1.0000,  0.0000],
        [ 1.0000,  0.0000,  1.0000],
        [ 0.5000,  1.0000,  0.0000]])